apiVersion: v1
kind: Service
metadata:
  name: {{ include "fibo-fastapi.fullname" . }}
  labels:
    {{- include "fibo-fastapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.ports }}
    {{- range .Values.service.ports }}
    - name: {{ .name | default (printf "port-%d" .port) }}
      port: {{ .port }}
      targetPort: {{ .targetPort | default "http" }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
    {{- else }}
    - name: http
      port: {{ .Values.service.port }}
      targetPort: "http"
      protocol: TCP
    {{- end }}
  selector:
    {{- include "fibo-fastapi.selectorLabels" . | nindent 4 }}
